### ISSUE TITLE
quotation marks being changed

### ISSUE THREAD

**Issue by Kosai106** [lukakerr/feather#15]
I have some Regex using " marks, but for whatever reason, Feather wants to convert these into ” and it's making it a pain to work with.

## Example:

[![https://gyazo.com/1a6fc25323c8a85fc33bd55dff7d440d](https://i.gyazo.com/1a6fc25323c8a85fc33bd55dff7d440d.gif)](https://gyazo.com/1a6fc25323c8a85fc33bd55dff7d440d)

**Comment by lukakerr** [comment]
Hmm, I cant reproduce this. Do you by chance have `Edit -> Substitutions -> Smart Quotes` turned on?

**Comment by Kosai106** [comment]
Ahh, I did. Are these `Substitutions` documented somewhere?

**Comment by lukakerr** [comment]
They are just the generic menu options under an Edit menu when you have an NSTextView in your app that accepts rich text
